services:
  foodtruck:
    image: bentoluizv/foodtruck-project:latest
    container_name: foodtruck
    restart: always
    env_file:
      - .env
    networks:
      - shared_network
      - foodtruck_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - foodtruck_network

  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - foodtruck_network

volumes:
  postgres_data:
  redis_data:

networks:
  shared_network:
    external: true
    name: shared_network
  foodtruck_network:
