"""add-website-role

Revision ID: 717108abc1d0
Revises: ca713c51cd3c
Create Date: 2025-09-07 00:54:15.758396

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '717108abc1d0'
down_revision: Union[str, None] = 'ca713c51cd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add 'website' value to userrole enum if it does not exist
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'website';")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('orderitem_order_id_fkey'), 'orderitem', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'orderitem', 'order', ['order_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('orderitem_order_id_fkey'), 'orderitem', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('orderitem_order_id_fkey'),
        'orderitem',
        'order',
        ['order_id'],
        ['id'],
    )
    # ### end Alembic commands ###
