"""update-user-model

Revision ID: a0c4db552383
Revises: 8649a7b6eb8e
Create Date: 2025-05-29 03:14:03.522065

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0c4db552383'
down_revision: Union[str, None] = '8649a7b6eb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('username', sa.String(length=20), nullable=False)
    )
    op.add_column(
        'user', sa.Column('full_name', sa.String(length=100), nullable=True)
    )
    op.create_index(
        op.f('ix_user_username'), 'user', ['username'], unique=True
    )
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'name', sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
